# Generated by Django 4.1 on 2023-11-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloque', '0002_bloque_reserva_stock_delete_date_reserva_idstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='idStock',
        ),
        migrations.AddField(
            model_name='reserva',
            name='idStock',
            field=models.ManyToManyField(to='bloque.stock'),
        ),
    ]
