# Generated by Django 4.1 on 2023-11-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloque', '0004_stock_bloque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='idStock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bloque',
        ),
        migrations.AddField(
            model_name='bloque',
            name='idstock',
            field=models.ManyToManyField(to='bloque.stock'),
        ),
    ]
