# Generated by Django 4.1 on 2023-11-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloque', '0005_remove_reserva_idstock_remove_stock_bloque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cantE',
        ),
    ]
