# Generated by Django 4.1 on 2023-11-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloque', '0007_rename_idstock_bloque_ide'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='idE',
            field=models.ManyToManyField(to='bloque.stock'),
        ),
    ]
