# Generated by Django 4.1 on 2023-12-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloque', '0008_reserva_ide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='idE',
        ),
    ]
