# Generated by Django 4.1 on 2023-12-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloque', '0010_remove_reserva_idb_reserva_ide'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='idB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloque.bloque'),
        ),
    ]
