# Generated by Django 4.1 on 2023-12-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloque', '0011_reserva_idb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='idE',
        ),
    ]
