# Generated by Django 4.1 on 2023-12-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_project_profile_project'),
        ('bloque', '0012_remove_reserva_ide'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='proyecto_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.project', verbose_name='Proyecto del Usuario'),
        ),
    ]
