# Generated by Django 4.1 on 2023-12-20 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloque', '0013_reserva_proyecto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='idB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloque.bloque', verbose_name='ID de Bloque'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nomA',
            field=models.CharField(max_length=25, verbose_name='Nombre Usuario'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='idE',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Stock'),
        ),
    ]
